In [1]:
import numpy as np

# create 1D numpy array
a = np.array([1, 2, 3, 5, 8])
print(type(a))
print(a.shape)
print(a.dtype)
print(a)

<class 'numpy.ndarray'>
(5,)
int64
[1 2 3 5 8]


In [3]:
a = np.array([1, 2, 3, 5, 8], dtype='float32')
print(a.dtype)

float32


In [4]:
print(a[0], a[1], a[-1])
print(a)

1.0 2.0 8.0
[1. 2. 3. 5. 8.]


In [5]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print (b.shape)
print (b[0, 0], b[0, 1], b[1, 0])
print('2D matrix:', b)

(2, 3)
1 2 4
2D matrix: [[1 2 3]
 [4 5 6]]


In [6]:
c = np.ones((3, 4))
print(c.shape)
print('c:', c)
c = np.zeros((2, 2))
print('c:', c)

(3, 4)
c: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
c: [[0. 0.]
 [0. 0.]]


In [7]:
d = np.eye(4) # Create a 2x2 Identity matrix
print (d)
e = np.random.random((2, 2))  # Create an array filled with random values
print (e)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.70312608 0.21772156]
 [0.45206509 0.22505218]]


In [8]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)
b = a[:2, 1:3]
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]


In [9]:
ex = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
ex[1:7:2] #from 1 to 6th index skipping 1 index

array([2, 4, 6])

In [14]:
a = np.array([[1, 2], [3, 4], [5, 6]])

bool_idx = (a > 2)

print(bool_idx)
print ('using bool index:', a[bool_idx])
print ('direct:', a[a > 2])

[[False False]
 [ True  True]
 [ True  True]]
using bool index: [3 4 5 6]
direct: [3 4 5 6]


In [15]:
x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[5, 6], [7, 8]], dtype=np.float64)

# Element wise sum; both produce this array
# "[[6.0 8.0]
#  [10.0 12.0]]"
print(x + y)
print(np.add(x, y))

# Element wise subtraction
# "[[-4.0 -4.0]
#  [-4.0 -4.0]]"
print(x - y)
print(np.subtract(x, y))

# Element wise multiplication
# "[[  5.  12.]
#  [ 21.  32.]]"
print(x * y)
print (np.multiply(x, y))

# Element wise division
# "[[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]"
print (x / y)
print (np.divide(x, y))

# Element wise Square root 
# "[[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]"
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [16]:
import numpy as np

a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
b = a.reshape(3, 4)

In [18]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])